"""fix_chapter_section_self_referential_relationships

Revision ID: 8111c818611b
Revises: 1871f43d18aa
Create Date: 2025-09-07 23:18:29.571206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8111c818611b'
down_revision = '1871f43d18aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chapter', schema=None) as batch_op:
        batch_op.add_column(sa.Column('chapter_order', sa.Integer(), nullable=True))
        batch_op.drop_constraint('chapter_parent_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('chapter_chapter_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'chapter', ['parent_id'], ['id'])
        batch_op.drop_column('section_order')
        batch_op.drop_column('chapter_id')

    with op.batch_alter_table('section', schema=None) as batch_op:
        batch_op.add_column(sa.Column('chapter_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'chapter', ['chapter_id'], ['id'])
        batch_op.drop_column('chapter')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('section', schema=None) as batch_op:
        batch_op.add_column(sa.Column('chapter', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('chapter_id')

    with op.batch_alter_table('chapter', schema=None) as batch_op:
        batch_op.add_column(sa.Column('chapter_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('section_order', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('chapter_chapter_id_fkey', 'chapter', ['chapter_id'], ['id'])
        batch_op.create_foreign_key('chapter_parent_id_fkey', 'section', ['parent_id'], ['id'])
        batch_op.drop_column('chapter_order')

    # ### end Alembic commands ###
